name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update known hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -t rsa 107.20.108.41 >> ~/.ssh/known_hosts

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: composer update
        run: composer update
      - name: Install dependencies
        run: composer install --no-dev

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS EC2
        run: |
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AWS_ACCESS_KEY_ID }}@${{ secrets.AWS_INSTANCE_IP }} '
          cd /var/www/html && 
          git pull && 
          composer install - no-dev && 
          php artisan migrate - force && 
          php artisan optimize
          '

    